#dubbo 配置
spring:
  dubbo:
    application:
      name: course-service
    registry:
      address: zookeeper://192.168.1.8:2181
    protocol:
      name: dubbo
      port: 20880
    scan: com.imooc.course
#数据源的配置
  datasource:
    url: jdbc:mysql://192.168.1.8:3306/db_course
    username: root
    password: aA111111
    driver-class-name: com.mysql.jdbc.Driver

thrift:
  user:
    ip: user-service
    port: 7911