version: '3'

networks:
  default:
    external:
      name: cloud-network

services:
  message-service:
    image: message-service:latest

  user-service:
    image: user-service:latest
    command:
      - "--mysql.address=127.0.0.1:3306"

  api-gateway:
    image: api-gateway:latest
    links:
      - message-service
      - user-service
    ports:
      - 8080:8080