version: '1'

networks:
  default:
    external:
      name: cloud-network

services:
  message-service:
    image: message-thrift-service:latest

  user-service:
    image: user-service:latest
    command:
    - "--mysql.address=172.19.0.2"

  user-edge-service:
    image: user-edge-service:latest
    links:
    - user-service
    - message-service
    command:
    - "--redis.address=172.19.0.3"

  course-service:
    image: course-service:latest
    links:
    - user-service
    command:
    - "--mysql.address=172.19.0.2"
    - "--zookeeper.address=172.19.0.4"

  course-edge-service:
    image: course-edge-service:latest
    links:
    - user-edge-service
    command:
    - "--zookeeper.address=172.19.0.4"

  api-gateway-zuul:
    image: api-gateway-gateway:latest
    links:
    - course-edge-service
    - user-edge-service
    ports:
    - 8080:8080