version: '1'

networks:
  default:
    external:
      name: cloud-network

services:
  message-service:
    image: message-service:V1.0

  user-service:
    image: user-service:V1.0
    command:
      - "--mysql.address=172.19.0.2:3306"

  api-gateway:
    image: api-gateway:V1.0
    links:
      - message-service
      - user-service
    ports:
      - 8080:8080