version: "3.4"
services:
  message-service:
    image: hub.cloud.com:8080/microservice/message-service:V1.0
    deploy:
      endpoint_mode: dnsrr
      resources:
        limits:
          cpus: "0.2"
          memory: "128M"

  user-service:
    image: hub.cloud.com:8080/microservice/user-service:V1.0
    deploy:
      endpoint_mode: dnsrr
      resources:
        limits:
          cpus: "0.2"
          memory: "512M"

  api-gateway:
    image: hub.cloud.com:8080/microservice/api-gateway:V1.0
    deploy:
      endpoint_mode: vip
      resources:
        limits:
          cpus: "0.2"
          memory: "512M"
    ports:
      - "8080:8080"
    depends_on:
      - message-service
      - user-service

networks:
  default:
    external:
      name: cloud-overlay
