server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      # 与服务注册于发现组件进行结合，通过 serviceId 转发到具体的服务实例
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

#      routes:
#      - id: user-service
#          uri: http://localhost:8031
#          predicates:
#            - Path=/config/**
#          filters:
#            - StripPrefix=1