server:
  port: 8031

spring:
  application:
    name: user-thrift-service
  #数据源的配置
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.1.8:3306/micro_service
    username: root
    password: Yuhan123456