server:
  port: 8020

spring:
  application:
    name: config-center-bus
  cloud:
    # git配置方式
    config:
      server:
        git:
          uri: https://github.com/Lengxiaobing/config-center.git
          # git仓库地址下的相对地址，可以配置多个，用,分割。
          search-paths: microservice
          username:
          password:
    # 开启跟踪总线事件
    bus:
      trace:
        enabled: true
  # RabbitMQ
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest

# Web管理端点的配置属性
management:
  endpoints:
    web:
      exposure:
        include: bus-refresh

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka/
