spring:
  application:
    name: eureka-registration-center
server:
  port: ${server.port}
eureka:
  instance:
    hostname: ${spring.application.name}
    appname: ${spring.application.name}
    prefer-ip-address: false
    lease-expiration-duration-in-seconds: 90
  server:
    enable-self-preservation: true
    eviction-interval-timer-in-ms: 5000
  client:
    register-with-eureka: true
#    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/,http://${eureka.node.hostname}:${eureka.node.port}/eureka/