server:
  port: 8032
spring:
  application:
    name: user-edge-service
  redis:
    host: 192.168.3.60
    port: 6381
    timeout: 20000
    database: 6
    password: Yuhan123456
    sentinel:
      master: mymaster
      nodes: 192.168.3.60:26379,192.168.3.167:26379,192.168.3.168:26379

thrift:
  use:
    ip: user-service
    port: 8031
  message:
    ip: message-service
    port: 8030