server:
  port: 8020

spring:
  application:
    name: config-center
  cloud:
    # git配置方式
    config:
      server:
        git:
          uri: https://github.com/Lengxiaobing/spring-cloud.git
          # git仓库地址下的相对地址，可以配置多个，用,分割。
          search-paths: spring-cloud
          username:
          password:

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka/
